---
- name: Copy certificate from server to localhost
  fetch:
    src: "{{ item }}"
    dest: certs/
    flat: true
  with_items:
    - "{{ strongswan_swanctl_root_dir }}/x509ca/ca-cert.pem"
    - "{{ strongswan_swanctl_root_dir }}/x509/cert.pem"
