---
- name: Copy certificate from localhost to client
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: "{{ playbook_dir }}/certs/ca-cert.pem"
      dest: "{{ strongswan_swanctl_root_dir }}/x509ca/ca-cert.pem"
    - src: "{{ playbook_dir }}/certs/cert.pem"
      dest: "{{ strongswan_swanctl_root_dir }}/x509/cert.pem"
